wireapp/rusty-jwt-tools

- jwt/Cargo.toml
- jwt/src/alg.rs
- jwt/src/dpop.rs
- jwt/src/error.rs
- jwt/src/generate_dpop_access_token.rs
- jwt/src/generate_dpop_token.rs
- jwt/src/jwk.rs
- jwt/src/lib.rs
- jwt/src/test_utils.rs
- jwt/src/verify_dpop_token.rs
----
----
Support P384 EcDSA signature scheme
----
> feat: support P384

- .github/workflows/deny.yml
- LICENSE
- deny.toml
- jwt-ffi/Cargo.toml
- jwt/Cargo.toml
----
----
Add [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/) license and a CI step to verify all crates used verify it.
----
> build: add MPLv2 license and verify it

- Cargo.toml
- jwt/Cargo.toml
- jwt/src/access/mod.rs
- jwt/src/dpop/mod.rs
- jwt/src/error.rs
- jwt/src/jwe/alg.rs
- jwt/src/jwe/mod.rs
- jwt/src/lib.rs
- jwt/src/model/client_id.rs
- jwt/src/model/nonce.rs
- jwt/src/oidc/context.rs
- jwt/src/oidc/credential.rs
- jwt/src/oidc/datetime.rs
- jwt/src/oidc/issuer.rs
- jwt/src/oidc/mod.rs
- jwt/src/oidc/presentation.rs
- jwt/src/oidc/proof.rs
- jwt/src/oidc/util.rs
- jwt/src/test_utils/mod.rs
----
----
Added methods for
* encrypting a JWE
* decrypting a JWE
----
> feat: initial support for JWE

- acme/src/account.rs
- acme/src/authz.rs
- acme/src/certificate.rs
- acme/src/chall.rs
- acme/src/directory.rs
- acme/src/docker.rs
- acme/src/finalize.rs
- acme/src/identifier.rs
- acme/src/lib.rs
- acme/src/order.rs
- e2e-identity/README.md
- e2e-identity/src/lib.rs
- e2e-identity/src/types.rs
- e2e-identity/tests/e2e.rs
> chore: end-to-end identity cleanup [CL-21]

- ffi/bindings/haskell/test/Spec.hs
> fix: Haskell test

- acme/src/identifier.rs
- acme/src/order.rs
- cli/src/access_generate.rs
- cli/src/access_verify.rs
- e2e-identity/README.md
- e2e-identity/src/lib.rs
- e2e-identity/tests/api.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/fmk.rs
- e2e-identity/tests/utils/wire_server/server_api.rs
- jwt/src/access/generate.rs
- jwt/src/access/mod.rs
- jwt/src/dpop/generate.rs
- jwt/src/dpop/mod.rs
- jwt/src/jwt/verify.rs
- jwt/src/model/client_id.rs
- jwt/src/test_utils/access.rs
- jwt/src/test_utils/dpop.rs
----
----
In the public API, expect a qualified client id with delimiter `:` and internally convert it into `/`
----
> feat: different qualified client id

- acme/Cargo.toml
- acme/src/certificate.rs
- acme/src/error.rs
- e2e-identity/Cargo.toml
- e2e-identity/README.md
- e2e-identity/src/lib.rs
- e2e-identity/tests/utils/display.rs
- e2e-identity/tests/utils/fmk.rs
- ffi/bindings/haskell/test/Spec.hs
----
----
Because it does not requiring parsing when consumed.
Also pay attention to zeroize private key material
----
> feat!: certificate_response return DER encoded certificates

- acme/Cargo.toml
- cli/Cargo.toml
- e2e-identity/Cargo.toml
- ffi/Cargo.lock
- ffi/Cargo.toml
- jwt/Cargo.toml
> build: 0.3.4

- .github/workflows/audit.yml
- .github/workflows/coverage.yml
- .github/workflows/deny.yml
- .github/workflows/rust.yml
> build: fix coverage job and migrate to dtolnay Rust installers

- acme/src/order.rs
- ffi/src/lib.rs
- jwt/src/access/generate.rs
- jwt/src/access/mod.rs
- jwt/src/dpop/generate.rs
- jwt/src/dpop/mod.rs
- jwt/src/error.rs
- jwt/src/jwt/verify.rs
- jwt/src/test_utils/dpop.rs
----
----
Prevents any issue that might appear when clock drifts between client & server or the latter's clock is not monotonic
----
> fix: generate JWTs with "nbf" claim slightly in past

- e2e-identity/src/lib.rs
- jwt/src/model/alg.rs
- jwt/src/model/pem.rs
> feat: turn enrollment instance serializable [CL-167]

- acme/src/certificate.rs
- acme/src/finalize.rs
- acme/src/identifier.rs
- deny.toml
- e2e-identity/README.md
- e2e-identity/src/lib.rs
- e2e-identity/tests/api.rs
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/docker/stepca.rs
- e2e-identity/tests/utils/fmk.rs
- e2e-identity/tests/utils/wire_server/server_api.rs
- ffi/Cargo.lock
----
----
test templating the generated x509 certificate and add verifications in the certificate parsing step that the generated certificate contains the expected identity claims
----
> feat!: template certificate

- acme/Cargo.toml
- acme/src/certificate.rs
- acme/src/error.rs
- acme/src/identity.rs
- e2e-identity/src/builder.rs
- e2e-identity/src/lib.rs
- ffi/Cargo.lock
> feat: helpers to assist credential rotation [WPB-1185]

- acme/src/identity.rs
- e2e-identity/README.md
- e2e-identity/src/builder.rs
- e2e-identity/tests/api.rs
- e2e-identity/tests/utils/docker/stepca.rs
- jwt/src/model/client_id.rs
> fix: userId base 64 encoding [WPB-3572]

- .github/workflows/rust.yml
- Cargo.lock
- e2e-identity/README.md
- jwt/Cargo.toml
- jwt/src/access/generate.rs
- jwt/src/access/mod.rs
- jwt/src/dpop/generate.rs
- jwt/src/dpop/mod.rs
----
----
Due to synchronization issues with backend adding a more important leeway fixes that.
----
> fix: add leeway to iat & nbf [WPB-4947]

- Cargo.lock
- e2e-identity/Cargo.toml
- e2e-identity/README.md
- e2e-identity/src/builder.rs
- e2e-identity/tests/e2e.rs
> fix: WireIdentityBuilder was not tested. Now supports unqualified handle

- e2e-identity/README.md
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/docker/dex.rs
- e2e-identity/tests/utils/docker/ldap.rs
- e2e-identity/tests/utils/docker/mod.rs
- e2e-identity/tests/utils/docker/stepca.rs
- e2e-identity/tests/utils/docker/wiremock.rs
- e2e-identity/tests/utils/fmk.rs
- e2e-identity/tests/utils/mod.rs
----
----
* get rid of false positive e2e tests by adding explicit errors.
* turn docker image version dynamically parameterizable by using env variables
----
> test: better e2e tests

- .github/workflows/semantic-commit-lint.yml
- jwt/src/lib.rs
This causes build failures when building these crates with crate2nix, which builds each crate in isolation (without access to all the sources).
----
----
_Briefly describe how this change was tested and if applicable the exact steps taken to …
> docs(jwt): don't reach outside of crate boundary

- Cargo.lock
- Cargo.toml
- acme/Cargo.toml
- cli/Cargo.toml
- e2e-identity/Cargo.toml
- e2e-identity/README.md
- jwt/Cargo.toml
> build: rebase jwt-simple and add feature to remove rsa from dependencies [WPB-5705]

- e2e-identity/README.md
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/display.rs
- e2e-identity/tests/utils/fmk.rs
- jwt/src/oidc/mod.rs
> test: fix openssl command

- acme/src/certificate.rs
- acme/src/finalize.rs
- e2e-identity/README.md
- e2e-identity/src/lib.rs
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/fmk.rs
- jwt/src/oidc/mod.rs
> fix: use different keys for CSR signing and ACME account as recommended by RFC8555 Section 11.1

- acme/src/authz.rs
- acme/src/certificate.rs
- jwt/src/test_utils/dpop.rs
----
----
Read more thoroughly RFC 8555 and add additional checks
----
> fix: rfc 8555 checks

- Cargo.lock
- acme/src/certificate.rs
- e2e-identity/README.md
- x509-check/Cargo.toml
- x509-check/src/lib.rs
- x509-check/src/revocation.rs
> fix: we were trying to decode ski & aki as utf-8

- Cargo.lock
- x509-check/Cargo.toml
- x509-check/src/revocation.rs
> fix: Forbid self-signed End-identity certs [WPB-1190]

- Cargo.lock
- x509-check/src/revocation.rs
> fix: Rework x509 verification to be sturdier

- acme/Cargo.toml
- acme/src/identity/mod.rs
> feat: add serial number, not before & not after in the identity object

- Cargo.lock
- e2e-identity/Cargo.toml
> fix: Use vendored OpenSSL for testing

- acme/src/certificate.rs
- acme/src/identity/mod.rs
- e2e-identity/src/builder.rs
- e2e-identity/src/lib.rs
- e2e-identity/tests/api.rs
- e2e-identity/tests/utils/docker/keycloak.rs
- e2e-identity/tests/utils/fmk.rs
- x509-check/src/lib.rs
> fix: verify revocation when checking the status

- x509-check/src/revocation/crl_info.rs
- x509-check/src/revocation/misc.rs
> fix: revocation not working

- e2e-identity/tests/e2e.rs
> test: fix/remove invalid/irrelevant e2e tests [WPB-7018]

- acme/src/identity/mod.rs
- acme/src/identity/thumbprint.rs
- acme/src/lib.rs
- e2e-identity/src/lib.rs
> feat: add method to compute a JWK thumbprint from a raw key [WPB-5975]

- Cargo.lock
- Cargo.toml
- acme/Cargo.toml
- acme/src/error.rs
- acme/src/finalize.rs
- acme/src/identity/mod.rs
- acme/src/identity/thumbprint.rs
- cli/src/access_generate.rs
- cli/src/jwk.rs
- cli/src/pem.rs
- e2e-identity/src/lib.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/keys.rs
- jwt/Cargo.toml
- jwt/src/access/generate.rs
- jwt/src/dpop/generate.rs
- jwt/src/jwk/ecdsa.rs
- jwt/src/jwt/generate.rs
- jwt/src/model/pk.rs
- jwt/src/test_utils/access.rs
- jwt/src/test_utils/dpop.rs
- jwt/src/test_utils/jwk.rs
- jwt/src/test_utils/mod.rs
- jwt/tests/e2e.rs
- x509-check/src/revocation.rs
> feat: Support p521 x509 validations [WPB-8589]

- acme/src/account.rs
- acme/src/chall.rs
- acme/src/lib.rs
- e2e-identity/src/lib.rs
- ffi/src/lib.rs
- jwt/src/access/generate.rs
- jwt/src/access/verify.rs
----
----
fix new clippy warnings
_Attachments …
> style: fix clippy warnings

- .config/nextest.toml
- Cargo.lock
- Cargo.toml
- README.md
- e2e-identity/build.rs
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/docker/dex.rs
- e2e-identity/tests/utils/docker/keycloak.rs
- e2e-identity/tests/utils/docker/ldap.rs
- e2e-identity/tests/utils/docker/stepca.rs
- e2e-identity/tests/utils/docker/wiremock.rs
- e2e-identity/tests/utils/fmk.rs
> test: fix testsuite [WPB-10397]

- .github/pull_request_template.md
> chore: .github: simplify the PR template

- acme/src/authz.rs
Explicitly check for the cases we allow, and let others result in an error.
> fix: acme: invert check for valid (identifier, challenge type) pairs [WPB-10103]

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- e2e-identity/tests/utils/display.rs
- ffi/bindings/haskell/src/RustyJwtToolsHs.hs
- ffi/bindings/haskell/test/Spec.hs
- ffi/shell.nix
This PR fixes the Haskell test and makes it run on CI, as well as adjust the test output so as not to clobber the README.md tracked by git.
> chore: more basic maintenance

- acme/src/certificate.rs
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/fmk.rs
Fail enrollment early in case the certificate is invalid.
----
> fix: improve validation of certificate response [WPB-10104]

- Cargo.lock
- Cargo.toml
- e2e-identity/Cargo.toml
- e2e-identity/README.md
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/docker/stepca.rs
- e2e-identity/tests/utils/fmk.rs
This PR fixes a few invalid signature verifications in the E2E test.
It also fixes incorrect intermediate CA cert generation, that was missing x509 name constraints.
> test: fix invalid signature verification in E2E test

- README.md
No need to push anything else.
> docs: README.md: just push the relevant tag

- e2e-identity/tests/e2e.rs
Amends https://github.com/wireapp/rusty-jwt-tools/pull/316
> Amend PR# 316 by providing a subsystem

- e2e-identity/Cargo.toml
- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/fmk.rs
This PR adds additional checks for the resulting certificate chain (see individual commits for details), as well as Bund-relevant markers.
> test: add additional tests for Bund [WPB-17039]

- e2e-identity/tests/e2e.rs
- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/fmk.rs
- e2e-identity/tests/utils/wire_server/oidc.rs
- e2e-identity/tests/utils/wire_server/server_api.rs
Nobody uses it and it doesn't bring any real value.
> test: e2e-identity: remove interactive Google test

- e2e-identity/tests/utils/cfg.rs
- e2e-identity/tests/utils/wire_server/mod.rs
> test: more minor cleanups
